### ISSUE TITLE
Working example of MQTT over LAN

### ISSUE THREAD

**Issue by biswajitkgp** [c-/ESP32-Ethgate#4]
First of all, congratulations on this amazing project, and thank you so much for sharing it online. You mentioned that you intended to use this as an ESP-NOW to (wired) MQTT gateway. Could you please share a working example code for MQTT?? It will be really helpful. Thanks in advance.

**Comment by c-** [comment]
Unfortunately, I had a bit of an accident the other day and wiped the firmware. Apparently I never got around to adding it to a git repo.

So now I need to rewrite it (or reconstitute it from my W5500 version).

**Comment by biswajitkgp** [comment]
Oh I'm so sorry to hear that. However, if you decide to reconstitute it, please upload it to GitHub this time. Thanks

**Comment by c-** [comment]
I've uploaded some very rough and ready firmware. It's not pretty, but it does actually work as an ESP-NOW-to-MQTT relay via the LAN.

Note that my ESP-NOW sensors basically transmit MQTT-ready chunks of data, so my relay code is tuned for that. YMMV.
